Vagrant.configure("2") do |config|
    # Verwendete Box (Vagrant-Boxen sind vorgefertigte virtuelle Maschinen)
    config.vm.box = "ubuntu/focal64"        

    # Konfiguration der Ressourcen (CPU, Speicher)
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024" # 1 GB RAM
      vb.cpus = 2        # 2 CPU-Kerne
    end

    # Freigabe des Verzeichnisses mit dem Go-Projekt
    config.vm.synced_folder "./", "/home/vagrant/project"

    # Port-Weiterleitung für den Go-Anwendungsport
    config.vm.network "forwarded_port", guest: 8080, host: 8080
  end
