apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service-app
  labels:
    app: checkout-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service-app
  template:
    metadata:
      labels:
        app: checkout-service-app
    spec:
      containers:
      - name: checkout-service
        image: svnelv/checkout-service:latest
        ports:
        - containerPort: 8080
