name: Notify on New Tag

on:
  push:
    tags:
      - '[A-Za-z0-9]+-service-[0-9]+.[0-9]+.[0-9]+'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Notify
        if: startsWith(github.ref, 'refs/tags/v') # Only notify if the tag starts with 'v'
        run: |
          echo "A new tag has been created: ${{ github.ref }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "By: ${{ github.actor }}"
          # Replace the following line with your notification method, e.g., sending an email, Slack message, etc.
          echo "Send notification to your desired platform"
